spring:
  # application name
  application:
    name: springSecurityJwt
  datasource:
    # h2
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  # jpa
  jpa:
    properties:
      hibernate:
        show_sql: true # sql show
        format_sql: true # pretty show
    hibernate:
      ddl-auto: create # db init (create, create-drop, update, validate, none)
  web:
    resources:
      add-mappings: false

jwt:
  secret: c3ByaW5nU2VjdXJpdHlKd3RQcmFjdGljZUtleUphbmdKam9sa2l0
